### ISSUE TITLE
Unable to control we-vibe Vector and Chorus

### ISSUE THREAD

**Issue by secondfolder** [buttplugio/buttplug#424]
**Describe the bug**
Using the latest version of Intiface Desktop (27.0.0) as well as numerous other web clients I tested out all the we-vibe devices I own. The we-vibe moxie and melt worked fine however I ran into issues with the Vector and the Chorus.

Both the Vector and Chorus would show up in the devices list and allow me to set the vibration level but this never actually vibrated the device. I tried then connecting both with the official we-vibe we-connect app and was able to control both from that app.

The IoST Index currently lists both devices as supported:
- https://iostindex.com/devices/WeVibe/Vector
- https://iostindex.com/devices/WeVibe/Chorus

**Additional context**
I'm not particularly familiar with Rust but I do have some technical skills so I could probably compile and test any patches with my toys if that is helpful.

**Comment by qdot** [comment]
Some WeVibe devices, including the Vector and the Chorus, require a specfic type of bluetooth radio (Cambridge Silicon Radio), and also require pairing to the desktop (CSR is the only radio that seems to handle this correctly).

Pick up something like https://www.amazon.com/Onvian-Bluetooth-Receiver-Transfer-Wireless/dp/B07G9TSDCG/ref=dp_prsubs_1?pd_rd_i=B07G9TSDCG&psc=1. Should work with all of your WeVibe toys, but will be needed for the Vector and Chorus.

We're going to see about popping better messages about this in the library, because it's a super weird/annoying problem that we unfortunately cannot fix in the library, as it's a driver/firmware level issue.

**Comment by secondfolder** [comment]
Oh rad! Thanks for that write up. I’ll buy one of those dongles and give it a shot :)
