### ISSUE TITLE
Add a generic Bluetooth device for DIY experiments

### ISSUE THREAD

**Issue by phckr** [buttplugio/buttplug#425]
I'd like to have a device type defined which uses bluetooth and has the following attributes:

BatteryService   -- standard Bluetooth API

The vibrateAttribute might be represented as a list of bytes (0 is off, 255 is max). The length of the string is the number of vibrate motors.

LinearAttribute -- represented similarly.

RotateAttribute -- Less clear what the standard representation should be.

Others?

This device protocol would be great for makers and allow them to experiment with their own devices.

Does this make sense?

And Yes, I would be prepared to work on this if only I could figure out how to build the JS client for the web.....

**Comment by qdot** [comment]
We already have this, it's t-code, which is what also drives the OSR-2/SR-6.

https://stpihkal.docs.buttplug.io/protocols/tcode.html

What it flies over is arbitrary in the system.

I'm planning on writing some documentation on interfacing DIY systems with Buttplug in the next month or so.

**Comment by phckr** [comment]
Thanks. I'll wait for your writeup as it still isn't obvious to me how to run the t-code protocol over bluetooth -- or even what GUIDs I should be using.

**Comment by qdot** [comment]
Are you familiar with Bluetooth LE? You should probably start there and figure out how to emulate a UART over it at minimum before approaching implementation under our library. We really just expect and build on proprietary LE services/characteristics in the first place.

**Comment by phckr** [comment]
Yes, I am familiar with BLE. There isn't a standard UART over BLE profile, but there are a number of common implementations (e.g. the Microchip Transparent UART Service, Nordic UART Service, etc). They seem to be fairly similar (just have a read and write channel with notifications) just with different UUIDs. 

The Microchip version has a simple Android App that can be used to emulate the client end of the UART link, so it makes it easy to test an implementation of a BLE gadget.

There is also no reason that a DIY gadget couldn't support both the UART interface and a more conventional characteristic interface.

**Comment by qdot** [comment]
Ok, I think that's where my confusion lies here. Almost no toy we support implements *any* sort of standard profile outside of the usually identification stuff and MAYBE battery (and a lot of toys implement their own battery protocol anyways. Sex Toys are not a bastion of engineering quality). Tcode just expects to be run over UART, which is why I usually recommend making a 2 characteristic read/write setup and calling it a day. We're working on adding the ability to autodetect the battery characteristic and host battery reading from that without having to specifically implement it in the protocol, but it's not done yet.

If you're curious (and a tl;dr on implementation), all of our device definitions live in a yaml file (that is just turned into json) here: https://github.com/buttplugio/buttplug/tree/master/buttplug/buttplug-device-config. We have a user config file that verifies against the same JSON schema and just adds/overwrites parts of the default. So really, if you already implement one of our protocols, there's no code changes needed to buttplug, it *should* all be addable in config files. Most of my life right now is writing the UI for those config files, before the documentation because I know otherwise I'm gonna get bombarded with questions on how to edit those files properly. :|
