### ISSUE TITLE
Adding Satisfyer Deep Diver

### ISSUE THREAD

**Issue by vollzeitlatte** [buttplugio/buttplug#454]
**Feature Description**

How can I add a new Satisfyer product? (on [eis.de](https://www.eis.de/p/satisfyer-satisfyer-deep-diver-mit-app-006796sf) (German))

**Comment by qdot** [comment]
Lemme tag in @blackspherefollower, they usually handle product additions.

**Comment by blackspherefollower** [comment]
@vollzeitlatte Looks like the deep diver is a single vibe Satisfyer, so it "should" just work; at least on Windows. I've noticed that the new Satisfyer devices's names are not prefixed by SF, so we'd need to test the device to exactly how it identifies in order to have the name displayed rather than a generic "Satisfyer Device".

**Comment by vollzeitlatte** [comment]
Can I help in some way?

**Comment by blackspherefollower** [comment]
If you've already got the device, I can guide you through some basic steps to get the name, but otherwise I'm not sure there's much to do.

I checked and EIS won't ship to me in the UK otherwise I'd have one on the way to me already.

Which OS are you on? I think you should be able to follow the steps here https://how.do.i.get.buttplug.in/hardware/satisfyer.html which should "just work", but Linux might be more troublesome.

**Comment by vollzeitlatte** [comment]
I could help with macOS, Windows with bluetooth stick. I will try it as soon as possible, probably tomorrow.

**Comment by blackspherefollower** [comment]
Oh, be aware that pairing Satisfyer devices on Windows only seems to work with CSR4 based BT4 dongles.

I'm tempted to take you up on the dropship offer, but once EIS lists a device, they usually turn up soon enough on the Satisfyer UK site (I bet it's the order in which the localised packaging gets printed). A few devices were added overnight, so I'll hold out for a bit then buy ~5 in one go.

**Comment by vollzeitlatte** [comment]
what are you doing with so many devices? :D

**Comment by blackspherefollower** [comment]
Very little... I enjoy picking the protocols apart far more than using most of the hardware I have. And in case you haven't seen, I run https://IoSTIndex.com where I document stuff alongside my notes over in the STPIHKAL issues: https://github.com/buttplugio/stpihkal/issues

**Comment by blackspherefollower** [comment]
Odd. I'd expect you to see an "unknown device", but it's also possible you've got the broken vendor drivers installed (there's a Bluetooth debugging section in the same FAQ docs with instructions for checking the drivers)
