### ISSUE TITLE
[Protocol spec] Step range property used in example but not defined.

### ISSUE THREAD

**Issue by Siege-Wizard** [buttplugio/buttplug#489]
**Describe the bug**
The v3 protocol spec Device List message example has a `StepRange` field that it not present in the Message Attributes section.
https://github.com/buttplugio/buttplug/blob/6f3e142966393fc5e55150130104da528f2052ee/spec/protocol-spec/enumeration.md?plain=1#L247

An equivalent `SensorRange` is present:
https://github.com/buttplugio/buttplug/blob/6f3e142966393fc5e55150130104da528f2052ee/spec/protocol-spec/enumeration.md?plain=1#L367-L371

**Expected behavior**
`StepRange` should be either dropped from the example if not supported, or added to the definition otherwise.

**Comment by qdot** [comment]
Yup, the PR you made is correct, StepRange shouldn't be exposed to the client, because there's no way for the client to do anything useful with that information. StepCount is really the only useful data there. I was originally going to switch StepCount to StepRange then ended up only using StepRange internally, but forgot to change the spec I had edited already.

**Comment by qdot** [comment]
#490 merged to master, should be rolled out to prod in a few minutes.
