### ISSUE TITLE
Consider adding observability to buttplugs (or other devices, etc)

### ISSUE THREAD

**Issue by buro9** [buttplugio/buttplug#503]
**Feature Description**

For those running something like a local Prometheus, it would be good to be able to have metrics generated.

The devices themselves don't possess such exporters, but perhaps the closest we could get is simple metrics from buttplug... this would at least export metrics of `power_state` where the labels would indicate the device type, device name, and the value the power state. But it could also include metrics for vibration power (or %), and so forth.

The purpose would be for people to have a local and private record of what their historical sessions included, the devices, levels and intensities.

**Comment by qdot** [comment]
Wow it's like you read my mind.

I am actually, seriously implementing the basis for this as we speak. If you watch the commits on the dev branch, there's a lot of work happening for "Server device access". This will be for exporting real time status updates of devices to our new Intiface Central application for histogramming there. Hadn't planned on prom metrics output but I work with pretty heavily with grafana stacks elsewhere so that could be an option.

**Comment by buro9** [comment]
It's the Grafana view... can I imagine a wall mounted display showing Grafana in a dungeon? I mean... why not?

But yeah, if all actions are logged, and all devices and their state have metrics... then that's pretty neat.

**Comment by qdot** [comment]
We have the hooks available for this throughout the server level now, if someone really wants to implement opentelemetry within intiface engine or intiface central, they probably could. This isn't really applicable to the base library tho, so closing.
