### ISSUE TITLE
Implement TCode extensions for additional features (NimbleStroker)

### ISSUE THREAD

**Issue by mnh86** [buttplugio/buttplug#551]
**Implement TCode extensions for additional device features (NimbleStroker)**

I have been working on adding support for a new device (NimbleStroker) using tcode-v03 config in intiface as a testbed (w/ linear position and vibrate cmds). This is all working great so far for Linear motion and Vibration controls.

Would like to see additional features added to buttplug.io to support additional t-code channels and Auxilliary axis controls.

For example, in my current [NimbleStroker tcode implementation](https://github.com/mnh86/NimbleTCodeSerial/blob/main/README.md#tcode-information) I have some extra Auxilliary axes defined:

>- `D2` - List available axes and user range preferences:
>  - `L0 0 9999 Up`: **Up/down position** linear motion (default: `5000`)
>    - Maps to NimbleStroker positions: -750 to 750
>  - `V0 0 9999 Vibe`: **Vibration intensity** (default: `0`)
>    - An oscillation is applied to the position when sent to the NimbleStroker.
>    - Maps to the amplitude of oscillation: 0 to 25 (position units)
>  - `A0 0 9999 Air`: **Auxilliary air in/out valve** (default `5000`)
>    - Value `0000` = air-out valve (looser)
>    - Value `5000` = stop valve (default)
>    - Value `9999` = air-in valve (tighter)
>  - `A1 0 9999 Force`: **Force command** (default `9999`)
>    - Maps to NimbleStroker force command values: 0 to 1023
>    - Controls the air pressure force of the actuator(?)
>  - `A2 0 9999 VibSpeed`: **Vibration speed** (default: `9999`)
>    - Maps to an oscillation speed for vibration: 0 to 20hz (default 20hz)

I had hoped I could add configuration to the intiface configuration file to expose those new `A#` channels to application clients, but it does not appear supported at this time. 

Straw-man example of what I was thinking...:
```
"tcode-v03": {
   "serial": [
     {
       "port": "COM3",
       "baud-rate": 115200,
       "data-bits": 8,
       "parity": "N",
       "stop-bits": 1
     }
   ],
   "defaults": {
     "name": "NimbleStroker Connectivity Module (Serial TCode v0.3)",
     "messages": {
       "LinearCmd": [
         {
           "StepRange": [
             0,
             100
           ],
           "ActuatorType": "Position",
           "FeatureDescriptor": "Up/Down Position (L0)"
         }
       ],
       "ScalarCmd": [
         {
           "StepRange": [
             0,
             100
           ],
           "ActuatorType": "Vibrate",
           "FeatureDescriptor": "Vibration (V0)"
         }
       ],
       "ScalarCmd": [
         {
           "StepRange": [
             0,
             100
           ],
           "ActuatorType": "Auxilliary",
           "TCodeChannelId": 1,                         // default is 0
           "FeatureDescriptor": "Force (A1)"
         }
       ]
     }
   }
 },
```
...where perhaps the channel number could be defined and described for additional controls. Same could apply to additional Linear axes, or other Scalar vibrator controls.

Current impl: https://github.com/buttplugio/buttplug/blob/master/buttplug/src/server/device/protocol/tcode_v03.rs 
T-code v3 spec: https://github.com/multiaxis/tcode-spec

**Comment by qdot** [comment]
This would need to be scaled back some, but otherwise should already work with no code changes to the library. 

Buttplug isn't made to map every single feature of every single device out there, especially not something as rare as the nimblestroker. It's made for mapping generic commands to large swaths of devices. The L0/V0 of your example config already work with our system. 

The Auxiliary would be out of scope for our library. For the rest of your functionality, it's recommended to build a specific library for the needs of the hardware, and prove out support new actuator types/commands/functionality first. This is why the OSR-2/SR-6 community has done, for instance.

**Comment by qdot** [comment]
@mnh86 You're not completely dead in the water for using Buttplug yet, it's just a matter of knowing what we (and by we I mean me) can support in the library versus what you can do yourself but not have to bring into mainline. There's multiple ways to tack on extra systems to Buttplug if you really want, including Raw Messages (https://docs.buttplug.io/docs/dev-guide/cookbook/devices-and-commands/raw-commands) and Websocket Devices (https://docs.buttplug.io/docs/dev-guide/inflating-buttplug/devices/intro).

For instance, we got a PR last year trying to integrate the Rez Trancevibrator, which doesn't work on Windows >7 due to USB issues. The recommendation there was that the device be supported as a Websocket Device, meaning the driver exists outside of Buttplug but could still be routed through the library on platforms that allow it.

**Comment by qdot** [comment]
Yeah this is all stuff that's buried in the library and either not documented, or very very newly documented. Happy to discuss alternatives more over on discord. :)

**Comment by sis92** [comment]
Do you have a solution for actuator device for SR6 or SSR2? (Linear + Rotation) or NimbleStroke (Linear + Vibration) ?

I am trying to use Intiface-central to manage those devices. However, I found it only shows devices supported in buttplug.io . It is not possible to customize a combination for TCode. Would you consider to make it flexible?
