### ISSUE TITLE
RFP: Commands for sensor handling.

### ISSUE THREAD

**Issue by hiss-remi** [buttplugio/buttplug#62]
This is going to start with a bit of a discussion on what I see us wanting out of a set of sensor control messages, because I think it'll make more sense that way.

On the one hand, we want things to be generic and intercompatible so that a client doesn't have to care so much about exactly what device is on the other end.

On the other hand, that's going to be rough, since we're dealing with devices that offer a wide variety of information in an assortment of unique and excitingly incompatible formats. 

Also not having a million different commands to cover it all seems like it would be good. Not that trying to make do-it-all commands doesn't sound it's own degree of perilous, but if dividing it up gives you a lot of basically similar things, it starts seeming a bit silly. Also, most will probably be relatively uncommon operations, so letting them 'take over' the spec doesn't make sense either.

I don't claim what I've come up with to be perfect (in particular the parameter names probably need work), but I think it should be able to cover these needs reasonably well.

**SensorCommand**

Sent to server. For asking a device about things it supports, telling it to start sending information, and telling it to stop. (Which could be divided into separate messages, but the first two would be nearly identical and the last trivial, so what's the point?)

Required parameters:

- CommandType: enum. Start, Stop, ... Inquire? Which of the three things mentioned above
- DataType: string. What kind of sensors we want to hear from. Battery, Accelerometer, LinearPosition, Buttons?, whatever useful stuff comes up. In a perfect world, this would be an enum, but since we don't know what might come up, a string seems safer. This shouldn't be a free-for-all though - if it could in some way be sensibly be treated as the same kind of data, it should have the same name here. Maybe case-insensitive?
- Raw: bool. If true, the format of data sent will be device-dependent and may not be immediately or easily comparable to data from different devices, but this may also allow additional options. If false, the data sent should be comparable to the same type of data from other devices, and passing options that would break this should give an error. Has no meaning for a Stop command, but I don't know if you can make a parameter 'semi-required'. (I'm not sure how often an obviously comparable standard will even be possible, but I think it's worth having the capability. Battery should be easy though - single float, 0.0 to 1.0.)

I don't see Inquire as trying to get a list of things a device supports, that could be super-messy if special options are involved. Just checks whether or not the given parameters would be valid for a given device.

Optional parameters:

- Frequency: How often to send data. Probably int in milliseconds? If this parameter is missing, send data as often as the device sends it (if appropriate). 0 requests data be sent once only.
- Options: Dictionary<string, string>. All the little things. Calibration values? Telling the device how often to send updates (when and where that's configurable)? Whether to send the launch buttons as on/off or as the raw value? All here. Very much device dependant, and in most cases only valid for 'raw' commands.

Parameters I'm not sure about at all:

- Filter: Asks the server to do some preprocessing of the data before sending it to the client. I'm not sure if this even belongs or if it should be left to the client entirely. But some things might come up often enough that a little preprocessing is worthwhile - debouncing switches, say, or ignoring small changes in acellerometer values. Probably a string.

**SensorData**

Sent from server. In cases where there will only be a single reply (and it's not an error), I'm not sure if it's more appropriate to send instead of an Ok or in addition to an Ok. Also used to respond to Inquire commands?

Required parameters:

- Device: Identify the data source device. Device index as uint looks to be the existing standard for this.
- DataType: string, matches the parameter from SensorCommand. The client may have requests going for multiple kinds of data at once. Probably shouldn't allow having multiple requests for the same type of data going at the same time.

Optional parameters:

- The actual data. Most things can be handled reasonably well by List<int> or List<float>. Maybe some things would want a string? Presumably, there has to be at least one kind of data attached, but I don't know if there's a way to require that in the json schema.

And that's pretty much what I've got. Though I could probably run up a demonstration branch showing how I see it working with Lovense devices (which, since I have one, is what I can develop for).

**Comment by qdot** [comment]
Ok, first off, thanks for submitting this with no template available! I've been poking at different ideas for RFP submission templates for a while, but I think actually working through a few test cases will make that easier, and you're gonna be the first one of those. :)

On that note, I should also say that I may get kind of long winded in some of these replies, as this is going to be the first time we've worked to develop messages in the open with the community, and I've got a lot to work out here on how contributions like this are going to work. It's something I've wanted to get started on, just been going about it slowly. In the end, I'd like to be able to put together a "What to think about when proposing new messages" part of the [Buttplug Developer Guide](https://buttplug-developer-guide.docs.buttplug.io), which we can add new sections to as we refine how we want the protocol to look.

**Comment by qdot** [comment]
Now, on to the actual meat of the RFP.

So, uh, wow. This is basically covering the whole other half of Buttplug that we haven't started on yet. Might as well start big. :)

Some background on our history with input (terms I'll use here are host relative, so output is commands to device, input is data from device). @blackspherefollower originally did some work on inputs when playing with Wiimote support in buttplugio/buttplug-csharp around last October. I ended up blocking that from landing because at the time we had next to no users, and no real idea of who needed what yet. I wanted to sit for a while with just output commands (vibrate, rotate, etc) and make sure the core system was solid before starting on adding input. I wouldn't say that we're teaming with developers at this point, but for the few we do have, we've already started getting questions about features like Battery levels. With the Lovense device detection implementation last month, I did a super quick and dirty implementation of characteristic notification reading, but as you found out and had to patch, it wasn't super well thought out, I just wanted a quick fix to our Lovense UUID updating issues.

Now, we've got reading code in C# (still need to implement it in JS :| ), but it's not really exposed anywhere other than Lovense device detection.

When considering adding new portions to the project like this, I usually tend to see what other projects are doing. For instance, I'm totally ripping this whole RFP idea off of Rust, albeit with far less formality because we're a tiny project that's not trying to standardize a programming language. For sensors I've been planning on looking at the W3C Generic Sensors spec to see what I can learn: https://www.w3.org/TR/generic-sensor/

I haven't actually had a chance to do that yet, but I'll leave the URL here for now and get to that in a later reply. As that's a web spec, it's once again going to be wildly over ambitious to get anything near that for our project, especially because our usage model is far different and more context specific than a web browser. There could be some structure in there we could crib off of though.

What follows from here is basically a stream-of-consciousness brain dump of my thinking about input so far. None of this is set in stone or "the way it's going to be", more just what I've been thinking so far and how I'd approach this with my understanding of the system as it is at the moment. I hope it makes sense, but I'm not guaranteeing anything. :)

> Also not having a million different commands to cover it all seems like it would be good.

I'm actually hoping to keep our command system fairly specific, because it'll lead to less confusion when implementing clients and servers and debugging remote protocols, and in a perfect world, we'd have client APIs ergonomic enough to hide the message building from the developer (we don't have that yet). 

Off the top of my head, here's a list of sensors we may need to support, both for hardware support that is currently implemented and planned for the future:

- Multi-axis accelerometer (Vstroker, Lovense, Wiimote*, Gamepads*)
- Multi-axis gyro (Wiimote*, Gamepads*)
- Digital Buttons (BKK Cup, Wiimote*, Gamepads*)
- Analog Axes (Ju-C Air, Gamepads*)
- Air Pressure? (Nogasm, Interactive Fleshlight, KGoal and other Kegelcizers)
- Battery (Almost anything Bluetooth)
- Analog Buttons? (Fleshlight Launch)
- Positional Feedback? (Nothing yet and Buttplug isn't made to be a control loop closer but throwing it in here for sake of argument)
- Biometrics? (Again, nothing yet, but definitely coming down the pipe)

* WiiMote and Gamepads are iffy, because I don't want to end up implementing a whole gamepad HID layer in Buttplug, but it's hard to figure out where that line needs to be drawn.

Please feel free to add things to that list if they're missing, would love it to be as comprehensive as we can get it though I know there's always going to be some random thing we're missing. I just noticed it's missing photoresistors, which were a common sensor on late 90s video sync sex toys, for instance. >.>

My original thought was the tackle these sensor types one at a time, as can be seen in bugs like buttplugio/buttplug-csharp#14, and that'd we'd have a message type for each of them. This architecture would be a bit more spread out than yours.

First off, were we to have a message per sensor type, device capabilities would be reflected across device support of the message type. For instance, assuming we relayed accelerometer data in the "AccelerometerSensorData" message, a Lovense Nora would have "AccelerometerSensorData" in its DeviceMessages dictionary on a DeviceAdd/DeviceList return, and the corresponding FeatureCount would be 3, as it's a 3-axis accelerometer (at least, I think it is). 

Now, the question is, what's in that AccelerometerSensorData message? Since the message name doesn't have a brand or model in it, that'd most likely be some sort of normalized readings. How we're gonna do that is something I haven't really thought through yet, but that was one of the reasons I blocked the Wiimote input implementation too, because I want our generic messages seriously thought through before we land them. In this system, the equivalent to your raw bool would most likely be something like "LovenseAccelerometerSensorData" which would just hand back the unprocessed values.

Your comment on frequency is something I haven't really considered too much on this issue, other than "discrete" and "streaming". For instance, we don't really need a battery power stream, we can just assume the developer will query for that when they want it. However, accelerometer values definitely need to stream.

Anyways, I'm gonna stop here, get some sleep, reread your proposal (and my rambling here because I most likely forget half of what I've just said by tomorrow), and take a look at the generic sensor spec, and then come back to this. Please lemme know your thoughts!

**Comment by hiss-remi** [comment]
This'll probably be a bit brief, since I want to get some things out there but don't have a lot of time right now.

> Now, we've got reading code in C# (still need to implement it in JS :| ), but it's not really exposed anywhere other than Lovense device detection.

Well, it's not that it'd be hard to do on other devices... as long as they're not indexed characteristics anyway. Not sure what the best approach to that will be. Especially considering the "multiple services" angle.

Although calling it "reading" might be confusing the issue. Reading was the thing that wasn't working because the characteristics involved don't support read. What we've got now is *listening*.

> I'm actually hoping to keep our command system fairly specific

Okay, fair enough. I think it's still worth having generic messages (the kind of thing I've proposed, if not exactly like them in detail) available to simplify development. It's sort of like the "foot in the door" thing I saw in some piece of documentation related to the ET-312 support. Maybe it's not ideal for "production" usage, but it's a base from which to build better tools for analyzing the data and determining how to normalize it. Right now it would be very awkward to share the work I've done with the lovense accellerometer, because it involves nonstandard changes to the message protocol. If one person can make a client with some good data visualization features, someone else does the low level hardware-end coding, and then anyone can use those things to poke around, that should help a lot with unanswered questions, and I think generic messages would help make that happen.

> Your comment on frequency is something I haven't really considered too much on this issue, other than "discrete" and "streaming". For instance, we don't really need a battery power stream, we can just assume the developer will query for that when they want it. However, accelerometer values definitely need to stream.

I just kinda like being able to do the battery thing event-style. Client says "tell me the battery level every five minutes", server says "kay", and we're off from there.

As for accellerometer data, it's actually possible with a Nora to configure it to send in a range varying from "faster than the bluetooth can actually handle, so you get multiple messages at once" to "about three times a second", but the relationship between the setting and the update speed is non-obvious so far. If it's desirable to have the client request messages at a certain rate (and it sounds like a good thing), it's going to take some server-side management to make that happen. And if a device uses read instead of notify, to present a consistent face to the client the server will need to run a polling loop, and if the client gets to ask for the speed there, it's back to needing the same thing for notify-based devices for consistency.

Possibly more thoughts after work.

**Comment by blackspherefollower** [comment]
Just going to throw out thoughts.

I think there's good reasons for both device specific and generic command sets: not everything fits into generic patterns, but those that do can be utilised much more easily by applications taking a generalist approach.

I'm the case of accelerometers, this probably means we can allow raw readings in a device specific context. For generic, they've got to be normalised.

I'd probably suggest rather that SensorCmd (which is equivalent to any input), maybe something slightly more specific and more descriptive: Subscribe<type> where type could be Battery, Accelerometer, Button, etc. This would make the feature count much clearer too, since the DeviceInfo would be able to describe how many of each type of sensor the device has. The command could also take a minimum interval value so that sensors for which interval readings make sense can rate limit.

It might be acceptable to have a SubscribeRawAccelerometer command which causes the server to send RawAccelerometerData messages back to the client. Since the message must include the device index (since you'd want to know which device the data is coming from), the client can work out what device type the raw data is from and interpret that data itself.

For clarity, I'd probably also suggest an Unsubscribe<type> message too

**Comment by qdot** [comment]
I'm now starting to work on the idea of sensors in #79 and #80, and long running messages in #83 and #84. I see individual sensor messages plus parametric structuring messages as the lowest level of what sensors and subscriptions will be built on, which is all I really care about for this repo. Making that easier for the user is going to be what the client API does, so the protocol doesn't really have to be ergonomic. I'm gonna go ahead and close this out, and break this down into smaller bugs, since this is way too much to tackle in one bug, and I feel like it's mixing ergonomics/presentation and information transfer, which while related, aren't explicitly tied to each other in this case.
