### ISSUE TITLE
Devices with no messages/features in config?

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#622]
While writing the conversion script for the new device config, I saw that there's some protocols (libo-karen and wevibe-legacy specifically) define no messages for a default device, and have no configurations otherwise. They still have connection information though, which means the device will connect then not show any features. 

@blackspherefollower Any reason we've still got these configs in the file?

**Comment by blackspherefollower** [comment]
The Karen is a sensor only device (which predated sensor support in the configs).

The WeVibe legacy stuff I think is more to catch if anyone turns up with a WeVibe Realm (Kiiroo licensed?) device.

I actually thought the Karen commented out, but I'd advocate for them to stay, so that they ever do turn up we'll get a support request.

**Comment by qdot** [comment]
Hmm, ok. I was considering making having no features forbidden by the schema so we catch these sort of things instead of accidentally shipping them, but I suppose using it as a "does anyone actually have this" is an interesting feature, so I'll keep it around.
