### ISSUE TITLE
C++ bindings?

### ISSUE THREAD

**Issue by sylvieee-iot** [buttplugio/buttplug#634]
Hello I am developing toy support for emulator written in C++. I am adapting https://github.com/dumbowumbo/buttplugCpp for this purpose, but I would love if I could use a library as well-maintained and feature-filled as this one.

Thank you for your time & your work on this project

**Comment by qdot** [comment]
Heh, well, this is the *main* library for the project which is why it's got all of the features. :)

buttplugCpp is a client for our system, which should get you far enough to be usable. Ideally, what your setup will look like is that your code will talk to [Intiface Central](https://intiface.com/central), which is basically a GUI wrapper around this repo. Was there something specific you were looking for?
