### ISSUE TITLE
RawCmd should be removed, changed to RawOutputCmd and RawSubscribeCmd(?)

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#66]
According to the spec, RawCmd just takes an integer array of up to 255 bytes (?!) and "sends it to a device". This has never been implemented anywhere, and we have many devices with multiple receive endpoints.

This message doesn't really work. It was one of the earliest ones I came up with, but I didn't really think through all of the types of device access we might end up with.

We need a RawOutputCmd that can take an endpoint name (and exposes them via a message feature), and possibly a RawSubscribeCmd (Better name for this?) that can take raw input from a device.

**Comment by blackspherefollower** [comment]
Given nothing ever used RawCmd, because it's never advertised by any devices, this is a case where it could be safe to remove the command from the schema; however, I think the safer pattern would be to leave it in the schema with some form of "deprecated" note on it and implement it in the server to simply return a deprecated command error.

Alternatively it could just assume the "Tx" endpoint, and error if that's not there (kind of like how SingleMotorVibrateCmd fronts VibrateCmd)

Another option is to keep the name, and add the endpoint as an optional parameter  (but this doesn't solve the naming issue). On that note, given the fact that the client APIs now abstract away from users needing to deal with the messages directly, is renaming the command really an issue?

**Comment by blackspherefollower** [comment]
I'm still an advocate for Read + Subscribe as separate verbs for inputs, but that's probably because I've been primarily working with BLE where the two are not necessarily the same

**Comment by qdot** [comment]
Closing and rerouting discussion to #95.
