### ISSUE TITLE
Multiple inputs are updated when only one is changed

### ISSUE THREAD

**Issue by ABoredBunny** [buttplugio/buttplug#660]
**Describe the bug**
The Moonhorn works where changing a pattern resets the current one. However this happens even when you send the same pattern it is on. Something is sending A constrict update when Vibration changes

**Expected behavior**
Vibration and Constriction are updated when the value changes. Which is what happens when you send a ScalarCmd with the same value.
You send 
**VIB: 0.1 CON: 0.2**
And after sends:
**VIB: 0.2 CON: 0.2**
And it only sends a bluetooth signal to updated VIB
So it should Send: **VIB: 0.2**

**Actual behavior**
When Vibration gets changed it also updates the Constriction. 
You send 
**VIB: 0.1 CON: 0.2**
And after sends:
**VIB: 0.2 CON: 0.2**
What it currently does
**VIB: 0.2 CON: 0.2**
It resends the Constrict value which interrupts the pattern. So it updates on the display but is restarted everytime VIB is updated.
This happens even when sending a command to only update Vibration, or change it on the Intiface interface.

**Additional context**
I already wrote about it in the Intiface issue tracker.

**Comment by blackspherefollower** [comment]
So... The JoyHub protocol "mostly" sets the levels of all features in a single command. If the features have been set otherwise without our knowledge, there's really nothing we can do to avoid resetting those.

Now, the "mostly" part is because some devices have the exception that the suction is controlled by a separate command, and there is a bug that we send that command even when the value hasn't changed if any of the other values have. That bug is fixed by https://github.com/buttplugio/buttplug/pull/658/commits/bcd7d41568ec0ad0256d15a00af848ea9ec8e21a

**Comment by ABoredBunny** [comment]
@blackspherefollower **Thanks,** those Hex patterns do seem like the ones I saw when I Wiresharked my bluetooth log. And that does seem to be the issue.

Although, I would need an android or linux version of Intiface with this to test if the issue is fixed. Or how to compile one.

**Comment by ABoredBunny** [comment]
@blackspherefollower Alright. I compiled a version of Intiface engine with https://github.com/buttplugio/buttplug/commit/bcd7d41568ec0ad0256d15a00af848ea9ec8e21a and it seems like Vibration does not Interrupt the pattern anymore. **Thanks for the great work!**

**Comment by blackspherefollower** [comment]
The issue should remain open until the PR is accepted

**Comment by blackspherefollower** [comment]
9bd12c9a5ff931e6cf87e88cec3f00856d48c18d is now out as part of 9.0.3
