### ISSUE TITLE
Project Proposal: Allow optional services and endpoints in the device config file

### ISSUE THREAD

**Issue by blackspherefollower** [buttplugio/buttplug#94]
Some devices that share a protocol with other devices from their brand may have additional endpoints that are not available on all the devices mapped to the protocol. Adding those endpoints to the config would cause the device -> protocol mapping to fail for the other devices because the endpoint isn't present.

An example:
The MagicMotion Kegel Master has a pressure sensor: this is the only device in the range that has one, but other than that the protocol is identical. Worse, it shares the same BLE name as it's predecessor the Kegel Twins (this means I can't move it into a new protocol to avoid the conflict without breaking support for that device).

Ideally, within the service: UUID { endpoints } block I'd have a section named optional that lists all the endpoints (potentially on other services) that we might be there.

For some devices this may be a prerequisite for the input aspects of #66 to be applicable

**Comment by qdot** [comment]
Ok, so this might fold in with the updates in #93. I'd be ok with an optional block I guess.

Though for the MagicMotion example you mentioned, is the extra service/characteristic the ONLY way to know the different between devices since they share a BLE name?

**Comment by blackspherefollower** [comment]
For the MagicMotion, so far yes. It's quite possible I've just missed a version number or more detailed name.

Another example, I just found out that the Vibratissimo devices give their real names via the generic manufacturer/device details service, but since the current logic is single service only, there's no trivial way to query those additional characteristics.

**Comment by qdot** [comment]
This may be something that's worth doing in the Device Comms (ne Subtype) Manager. USB descriptors have Manufacturer/Product name fields too, but there'd be no way to express that in the device description. I think we could make a generic "descriptor" object that Comms Managers can fill in, since USB descriptors are standardized, GATT has its own standards, etc.

**Comment by blackspherefollower** [comment]
I'll buy that. But there are still other devices than use multiple services, which may well be a BLE specific problem.

**Comment by qdot** [comment]
Oh, yeah, I'm still totally on-board with optional services too. Should probably break the descriptor system into its own issue.

**Comment by qdot** [comment]
Instead of making a special block, what if we just make all endpoints optional?

Here's what I'm thinking:

- Device is loaded via device config, creates whatever endpoints it can
- Protocol instance is built for device, is passed a list of endpoints created, plus everything over in #93 to know what messages we *think* the device should have.
- DeviceInfo is created from all this information. To have a message in the AllowedMessages dict, the device needs to have a config for it in the device config, and support all of the endpoint required in the protocol implementation.

For example, with the MagicMotion, this means we'll have the pressure endpoint, it'll just get ignored by anything that doesn't actually have the endpoint. The message attributes for pressure (once we figure out that message) will be set in the device config for whatever the device is (per #93), so via the combination of endpoint existing and message attributes in the device config, we should be able to support pressure for the one device that does, within a protocol that deals with multiple devices.

Does that sound ok?

**Comment by blackspherefollower** [comment]
That sounds doable, especially if the found endpoints can be queried during device setup: in the MagicMotion example, I haven't found a way to differentiate the twins Vs the master other than the presence of the extra service.

**Comment by qdot** [comment]
Yeah, I *think* that should be possible since I'm trying to unglue devices and protocols (as they're glued currently in js/C# but that won't work if I try to implement protocols and rust and devices in another language via FFI), so we can at least pass along endpoint lists into the protocol for setup.

**Comment by qdot** [comment]
Well, shit.

We've got 2 implementations doing 2 different things.

- C# allows this right now. If we have a characteristic in the configuration that doesn't match, we just keep going. See https://github.com/buttplugio/buttplug-csharp/blob/master/Buttplug.Server.Managers.UWPBluetoothManager/UWPBluetoothDeviceInterface.cs#L122
- JS doesn't allow this, but also doesn't actually check/throw. It just tries to get the characteristic then would throw an exception if it was wrong, meaning the whole device wouldn't connect AND we might not see it in logs. (WebBluetooth impl: https://github.com/buttplugio/buttplug-js/blob/master/packages/buttplug/src/server/managers/webbluetooth/WebBluetoothDevice.ts#L106, Node impl does the same thing.)

So, there's nothing to do on the C# side. You can go ahead and start adding the characteristics (on the "device-attributes" branch of the buttplug-device-config repo). For JS, I've filed https://github.com/buttplugio/buttplug-js/issues/213, should be an easy fix.
